branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: apple-event-hub-frontend
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: git
